server:
  port: 8191
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nimalangster/config-server-repo
          
          search-paths: # search in the folder pattern cos folder name doesnt appear in the uri
          - '*service'
          force-pull: true # by default get values from local repo this attibute force the service to get it from git url.
